<?php

/**
 * @file
 * Contains custom_module.module.
 */

use Drupal\custom_module\Entity\LogImuko;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_module module.
    case 'help.page.custom_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Module') . '</p>';
      return $output;

    default:
  }
}

function custom_module_user_login($account) {

  $datalog = [
    "tipo_log" => "Login { User Name: ". $account->getUsername()." }",
    "fecha" => strtotime(date("d-m-Y H:i:s"))
  ];
  $entity =  LogImuko::create($datalog);
  $entity->save();

}


/**
 * Implements hook_page_attachments().
 */
function custom_module_page_attachments_alter(array &$page) {
  $page['#attached']['library'][] = 'custom_module/jquery.validate';
  $page['#attached']['library'][] = 'custom_module/mylibrary';
}